server:
  port: 8084  # Gateway will run on port 8084

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/api/cars/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
  main:
    web-application-type: reactive

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/